version: '3.8'

services:
  spring:
    container_name: what-nail-todo-server
    image: ${DOCKER_USERNAME}/what-nail-todo-server:latest
    ports:
      - "8520:8080"
    depends_on:
      - redis
    networks:
      - app-network
    environment:
      - TZ=Asia/Seoul

  redis:
    container_name: what-nail-todo-redis
    image: redis:7.2
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6382:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network
    environment:
      - TZ=Asia/Seoul