services:
  redis:
    image: redis:latest
    container_name: joonseo-redis
    command: redis-server --requirepass imredis
    environment:
      - REDIS_PASSWORD=imredis
    ports:
      - 6379:6379
    networks:
      - es-bridge

  networks:
    es-bridge:
      driver: bridge