spring:
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false

  jackson:
    time-zone: Asia/Seoul
    serialization:
      fail-on-empty-beans: false

  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      password: ${REDIS_PASSWORD}

  security:
    jwt:
      access-token:
        expired-time: ${ACCESS_TOKEN_EXPIRED_TIME}
      refresh-token:
        expired-time: ${REFRESH_TOKEN_EXPIRED_TIME}
      secret: ${JWT_SECRET}

    oauth2:
      cookie:
        key:
          request: oauth2_authorization_request
          redirect-uri: redirect_uri
          expired-time: 10800000
      client:
        provider:
          naver:
            authorization-uri: "https://nid.naver.com/oauth2.0/authorize"
            token-uri: "https://nid.naver.com/oauth2.0/token"
            user-info-uri: "https://openapi.naver.com/v1/nid/me"
            user-info-authentication-method: header
            user-name-attribute: response

          kakao:
            authorization-uri: "https://kauth.kakao.com/oauth/authorize"
            token-uri: "https://kauth.kakao.com/oauth/token"
            user-info-uri: "https://kapi.kakao.com/v2/user/me"
            user-info-authentication-method: header
            user-name-attribute: id

        registration:
          google:
            client-id: ${OAUTH_GOOGLE_CLIENT_ID}
            client-secret: ${OAUTH_GOOGLE_CLIENT_SECRET}
            scope:
              - profile
              - email

          naver:
            client-id: ${OAUTH_NAVER_CLIENT_ID}
            client-secret: ${OAUTH_NAVER_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: Naver

          kakao:
            client-id: ${OAUTH_KAKAO_CLIENT_ID}
            client-secret: ${OAUTH_KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              - profile_image
              - profile_image
              - account_email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: Kakao

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_SERVER_USERNAME}
    password: ${MAIL_SERVER_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
  port: ${SERVER_PORT}

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace